.PHONY: all
all:
	ghdl -a mips_constant_pkg.vhd
	ghdl -a opcodes.vhd
	ghdl -a memory.vhd
	ghdl -a register_file.vhd
	ghdl -a flip_flop.vhd
	ghdl -a control_unit.vhd
	ghdl -a alu.vhd
	ghdl -a if_stage.vhd
	ghdl -a id_stage.vhd
	ghdl -a ex_stage.vhd
	ghdl -a mem_stage.vhd
	ghdl -a wb_stage.vhd
	ghdl -a IF_ID.vhd
	ghdl -a ID_EX.vhd
	ghdl -a EX_MEM.vhd
	ghdl -a MEM_WB.vhd
	ghdl -a processor.vhd
